### ISSUE TITLE
jekyll-redirect-from is a little unhappy

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#320]
```
       Deprecation: Collection#each should be called on the #docs array directly.
                    Called by /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-redirect-from-0.8.0/lib/jekyll-redirect-from/redirector.rb:13:in `generate_alt_urls'.
/home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-redirect-from-0.8.0/lib/jekyll-redirect-from/redirector.rb:41:in `is_dynamic_document?': cannot load such file -- jekyll/post (LoadError)
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-redirect-from-0.8.0/lib/jekyll-redirect-from/redirector.rb:47:in `has_alt_urls?'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-redirect-from-0.8.0/lib/jekyll-redirect-from/redirector.rb:14:in `block in generate_alt_urls'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-redirect-from-0.8.0/lib/jekyll-redirect-from/redirector.rb:13:in `each'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-redirect-from-0.8.0/lib/jekyll-redirect-from/redirector.rb:13:in `generate_alt_urls'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-redirect-from-0.8.0/lib/jekyll-redirect-from/redirector.rb:8:in `generate'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:154:in `block in generate'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:153:in `each'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:153:in `generate'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:58:in `process'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.0/lib/jekyll/command.rb:28:in `process_site'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:60:in `build'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:35:in `process'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/bin/jekyll:23:in `load'
	from /home/travis/build/newtheatre/history-project/vendor/bundle/ruby/2.1.0/bin/jekyll:23:in `<main>'
```

**Comment by wjdp** [comment]
Will be fixed with https://github.com/jekyll/jekyll-redirect-from/pull/76
