### ISSUE TITLE
ReferenceError: mapboxgl is not defined

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#616]
<del>https://app.getsentry.com/will-pimblett/new-theatre-history-project/issues/143008548/</del>
https://sentry.io/share/issue/38323935332e313433303038353438/

```
ReferenceError: mapboxgl is not defined
  at r.t.SnapshotRenderer.r.assignNewBody (/js/lib.js:3:19273)
  at r.t.SnapshotRenderer.r.replaceBody (/js/lib.js:3:17771)
  at None (/js/lib.js:3:17376)
  at r.t.Renderer.t.renderView (/js/lib.js:3:14750)
  at r.t.SnapshotRenderer.r.render (/js/lib.js:3:17326)
...
(7 additional frame(s) were not displayed)

ReferenceError: mapboxgl is not defined
```

**Comment by wjdp** [comment]
![image](https://cloud.githubusercontent.com/assets/1690934/16902960/d528451c-4c67-11e6-8aee-2cc780845481.png)

Worky on desktop, error was from mobile

**Comment by wjdp** [comment]
Seems to be tempremental, sticking in backlog but will keep an eye on sentry
