### ISSUE TITLE
Unable to fetch large album, fetch_image_urls fails

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#692]
```
Configuration file: /home/will/local/history-project/_config.yml
                  Source: /home/will/local/history-project
             Destination: /home/will/local/history-project/_site
       Incremental build: disabled. Enable with --incremental
            Generating... 
      Generating years... 
 Processing committees... 
      Processing shows... 
       Fetching SM album: 
       Fetching SM album: sFmqXq
  Fetching SM Image List: sFmqXq
      Fetching SM images: 792 at sizecustom
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /api/v2/image/7XkmZNs,vTcjgbx,szkRgmG,mjHm7ks,8Vhjd4W,P8SBpxJ,FfJ8DkT,CqgwK2S,zXZbxkV,GS2XD7f,w5xc6ST,p8XzgzZ,X6d4ZHn,CC2rdbz,f8LZwSh,DTCpMSB,hk253JM,F85LRpr,Bb6b2bj,D5tHxq8,FSwdHZM,9t5mwX2,CrhzXHG,ggDbWhB,vRMLnjr,9JFL6Sn,r3DvV9x,tcCsXnJ,wPVQp32,fxqWs3D,Zgxfztp,3KSmm95,V49RsN3,ks6sN86,KQqM9Bn,wGpcwMn,2JQkS9h,6Sq62jd,wzPp7Wm,qs77Tdm,tRXZwFj,WwpDJNd,zRnbcdH,vwHw4Zn,BfbScn4,sCLH32P,dRssFNN,V9xxNfn,3j83TrB,WhcVRHs,wWmTKP2,ZMkDpSj,6gN7Pv7,RnqcBTZ,xvMhkMQ,76BDV4k,J9mPCdG,R2wWX8C,8Qfz6vF,c4jHpr6,6jGKWqW,JGtcpMB,JdwxNJQ,779TX65,NZRmbsg,FkQRP7N,7hJpXKv,n27qqbh,qbx9QQ7,XDbpMRC,27797sZ,T52FWvh,PPJn4S8,VCtJH5j,dpWP2xg,fMHL5BL,WS3f4qd,ZSdvNvc,PQTbjhx,gSxHbs4,stgfgQZ,6jhQ5NR,2t9bBxf,XdcQcpN,rHVDLtj,DrR7KHN,3T7sWTs,PLMz3R2,kWZhX9G,hf9tqpw,x9HV9wb,MSSHKpr,VTjB6fD,cdMqBVk,RVv4KQp,qWq9XLc,x9XncFm,BR2ZDbW,3PN3LgD,fVx7nqv,krhGttS,VK2Zvqh,36VRwZm,z929jzs,57x7kvP,D7DGqxz,SJLMZcJ,3sbd28B,jHLW3Xt,kNPfm5P,QCDfpvr,7hf8rCr,Gq2c7FV,fHQHxGn,47zXzQd,3DRv63T,RGpHJXT,h5sGcgz,dB8SMrK,mz8XgMM,fbMCX7F,6Chm4Fd,k9jtFrR,LB5xKNs,x6tTRr7,ZX9sfjL,CK2RGS2,CGsv3C9,NsGvLMz,w7nmMMM,PZ7WJ7g,jqmTqs6,r5dD8WD,HbHcSwf,nn9VHJZ,cfj2Srx,ThMF8VJ,n6jVKBd,zM5bnLF,SHNPqkN,2RvRf2X,kxc85pB,f5C2DtX,TBtCdGP,vjnBDQv,w22Pn9n,v7MsJcT,HjD3Gds,m7rqGgZ,KGdrgv4,L4689zf,qMs7tbs,t33Fkr3,VKLcs6s,xvLcbQd,xBhQ4Lm,VPXKbbh,Snn9xfw,4XCzWbD,gSck3Vs,QFBXLNh,GCWhM2v,9nsv83m,SsgVdX2,DcmJB8c,NncrrpC,LvCDR49,hTzvqLt,FbFCqDZ,5GpXNgP,c9rm4rZ,mm7vLpq,7nrSSWx,B76SvvW,PH5WWtf,pzwXBPv,QkcLFjX,2F2KzbZ,QRVmM7f,QHQZLqL,KqcKJ4M,pBF7wLQ,7WRcDL8,HwTQMVR,W3czN3m,n8SnxkN,5HCRshf,fpSNh3V,H6s4qLN,hVr9PX7,WnV3Mg3,RRxnMwW,WMGnnhL,FtFZ9sz,kkc6dxw,DwbSFLb,xGM5Kvn,T9PPk4q,3BTHqMS,dRqR4BM,Hq6C2Sp,hdWmtQB,sCqR6Zv,j8JJKHt,Ndp9ST9,zJtcDQg,4JLPnJq,CgkLp6v,XPcjdS2,gtC2gXS,Rb7VwLb,fDq8X39,csxTSbQ,7wspNVt,ndJ9wBH,gzR6qGN,3tz5Kn6,gdwXVsx,QRjNsNw,Ft7G6GP,PLXDdvB,dLZQmgG,SRzX7SM,TWFLFBV,rn43L28,4LHpwf2,kCNLjHg,d8VRgr2,rF9T9nN,qKvCk6v,gQQ7x4Z,XDGvVfq,7t8wJ3J,PzbVv5w,hWfR9qJ,dR49PtH,56Swn2R,4VsjNwh,JpDkhHg,CQMMnwB,NqrX4qh,f6Vrf9M,MhzNncz,RxFVKxn,RRpVNvM,vCWNt9H,tz6pBhk,PqQSgsS,cXHNg3s,wDmHbtp,G3LLmmf,2jBD9mX,cHkdfct,S53bdMj,2BD3wXh,Wg6ZGLV,vKFF6LM,dqPcvrT,gwjnpwk,MqM2g9v,SzwXd9Z,3hpCKWV,qjSBJQk,DcTBt8d,BqV4nRm,gBBVLFd,chhZmqr,5MtM5fn,GPzRxgZ,gQh7QTg,qCrKDQq,HTmcCpt,tBhHW3G,HnqzLcM,d2Jq7hc,G2pLM3X,CV7HX42,wZj72Np,ZM8Mn87,JZCjcRh,G2QHksg,nZQrFXG,LgzLs6H,9gmW796,94RmgsL,qZ57fgz,Zbx4Jj2,sJ8BPNr,NScWxHc,N4Xq8Cv,BB6sLvw,S4JDnhs,nrH5gKG,NTQtpvg,cTMB4pp,whwc8Rk,7ZCtj8D,RJfFZQD,HLHrdzp,J4BRP8C,SXJqHNH,sZ5jQBQ,vBL79h4,mSCqMZd,dP6xzSK,sJGjMnq,3VB6GPh,jV8GQFR,fp3jqGs,SZVpqvP,sdXzhjc,VCkR39J,Ccd7Xm8,VHPXnsF,tZ3pkkz,VFHsRvV,JNFkBk9,RZWMFf7,DDsd7SK,qPSLV6H,jwGwfwz,7jq4TDd,TFZLZ7x,Sn4GqS3,WvRHDR3,B7Wwbv5,jrNvbdQ,H8nXgdZ,JmFKvWh,CknhmJv,6R27WPF,J83w6bt,LkV3GbR,LfS7JdS,zDZ394m,Rp9mMdm,vbDcLgB,F4KNTHL,QS7s4xV,vS79kwh,PB9hcGC,v5FdfnL,MqpXgSW,tbhJBRp,MWnhZKT,8s7k3TD,zrWsTRb,dtrPcHv,MjDSNWz,8LbSrhK,KCqCfhZ,3vNJDmW,xD4xKPH,3HLWSN7,ZqkPjXC,nMjCFkW,xXswpDn,wbj4mPr,fmwccVQ,whWCb48,z7JDhpN,v2g9MJz,Z79dCsz,QqKGLbv,dfWGqv6,bXs8kqp,hQV5jsP,rbTFmvT,cZ4MnPg,xRZD8zg,7fr2LsZ,gfsgW7n,JCRn9pW,xWLxBSn,RSDPc4L,Xc6qc3s,9XZt39H,rZKW493,PLTvX5B,dBQWrfm,ZSXsXVw,P6rHv4w,SJhphX2,k6CTX27,LKKBrqd,kPdxDc5,mqNpjrm,mCP8tHh,XbZCHcn,kHpd2mT,zhQ6pLH,3XtLPCX,XcnDdRk,VmRxssM,xKWrw5H,S5W9rhd,7gTWqvp,RgMmxP2,Z3QzXP5,TddZWgv,v6DH8c2,nrBCWr2,8sPjH9t,F4vbNMG,96C89xm,WbgLq9B,R86xg94,C5CLtQZ,H4RVP7w,LMZzfbT,QTn8BPH,vTQPdw6,d2pGtKJ,mLtwNcb,f3P4zcf,DNMDT95,SVpdnM9,vmZ5rRv,BJWN7bt,7QRDMmb,NpSCWwn,wtG3kgX,4w4fv2x,VR3LFqN,wcV5k8N,rZqb4Ns,B3b4rd8,FmqcK2h,CCMbBr9,kWKcStP,J2tJJs9,K4x55wJ,8TG67RK,5p65TvR,vzfd95s,dQPPSq9,JC6V4M4,RrCQ2Zh,DXwj6Br,vCHhjPZ,Sn3WF7Q,d2jRXgT,WvNbXdj,mW3c6Q5,Dzvfr9R,C43cBsw,8c7LzkB,9RQW5fv,F6ns3Mn,JPcfrv9,gGHFdhM,2pkMhxP,S9krJ76,BRJptwz,BCrzWBM,dJbMLGm,fhxsrNq,Pn3kX7D,wgBBtLg,JrksP6C,3Sj8QFW,5g9djQK,z2wzBRM,QSx6bQV,sxbt7DR,N8zgGj7,j9JDT9G,9vzFZ66,M2XJqXz,fL99MsN,sHPkVz7,7vNzdqH,zHf4S4n,rDFHhGc,PJF4L5k,vgDCCLp,nWsd34W,25cKqJV,vmHWmH7,pQrzbbz,59P4CmN,8ggpFnp,jQWsp5j,BPMNC7P,Fp8gfmD,LBT2Ncn,6nncMrk,6TD3RRb,38z7Rzq,7mHHFBs,hf4Nmzm,Brhccbx,VRsZFL5,NzvTHBd,QbSWQfc,9bBfJjh,g76h9Dq,x8V5pmp,5vxt5Lj,mb3RV8D,pGpRxwQ,NMn3Tt4,ZxBG9qQ,N5TSwsx,QthSDpx,rXsFXx4,T7q2mMb,LJ8pPn3,MLN9QRZ,RxDLNH6,c4ZwNMt,P5mk8m4,HjCrRh3,dBzCbtJ,rqLtg3Z,4Cm57Bk,sn3HGW3,5bMLbsm,zxZNN2w,n983MFr,zQQ3LCP,L9hWd78,jrDRjdS,CFxQcKf,t2DcNzv,6kFWMSR,Q6JHv24,zDbx2kh,pGjdPhw,pBhHbJ6,PtWnzPq,F6Cqgcq,XTKVRrV,8fWDBfr,4BJJ2nv,DKW6Cg5,KmDcg5P,FVgSX5M,TGqGjxt,8q9GxP2,ZZn3F9N,g8BB5d2,DGtXHZk,N9NMRWn,dtQ8w2K,32rqM84,LkmxKH8,94RFsBL,WMJX3m3,CR2P5Sn,pJSXnwx,scH6KSP,twxcq7v,zh3rr4T,W9C7tNQ,mkPPNps,DmpRj37,7gSdHTg,m7JJFgq,p5b42x7,VG9JwjQ,hc5skJM,4Lt3xjb,3Z6rd65,FGK4FHS,nCdNSh3,kbnQdXv,h44vLfM,J8Xdz2h,NDGqsgQ,2kncJnb,dzhw5nm,PGvr5dQ,C3pkcjJ,L6hBjNg,whf4qPV,zXFSVms,cP5dR8D,9x42xnn,WxHsnw2,nPxSzHg,swRqrCb,2j48tbn,Tbtzx5f,mbcC5Wp,MhdJhdP,kBPDcSC,6Ftsxcq,bFmCZrx,zWskSv6,rtKgrLq,TQCcqSR,zM3v3Db,ZTbT79P,K4CbX8k,F45Dn2N,tGzLtkj,XTJhRd4,Cg5rcF9,32rw8Qt,2NRm89k,KvJc3K7,d2ss4P3,vXB5rsp,f9wnn3T,5D9ndgd,MtpJKHt,hMstWxB,8zXhV8q,QR2cvKd,nvLZQSh,hX54NWT,J7M2GhM,5NTLr22,X5HqVZH,m3k3d5s,ZC499CR,CM4JDMP,TJtKqjN,CT5QWTB,k9gn2Xh,9Bm52xJ,WM8MDSv,rtWJdWg,k5L3X8L,Www792d,t8jXvw8,kWSdgNN,d6VdFW8,HwC8VDD,Qk4K8Kq,NCR9whs,ZXKzRJP,rqLLX6J,qbKBR3C,vjXCVfV,KrnZxt8,ZSBL43h,Bp56JkQ,gpTDQv3,D6FQqgV,n5R5nx2,P3DBtZM,FddgXJf,7JsC6Wd,fbJZwZM,NgTG5kk,G8WQVWx,V5QVGMv,QBfhzJ8,SchZthv,QkmNxKZ,Tgnv3T6,ZHKT99r,qp9dDbQ,hFRxQB6,vXFDw5P,dF8bjmF,jHm6mWs,97RhL3s,9Q9C5D4,BKx97HP,QpT8NHW,8nqj7wC,xxBqmL9,w3dBRNh,VnZ4227,cVdSRvp,7Z75PNm,pZD3T2d,vcXSKXc,5tNLgLR,dg6r6kN,QPLJn9s,5QczTbT,hPJcXKZ,HWRrCd6,53bCbxf,kNkngXh,v5rkMhH,7W4qTPM,jhqzZ6W,bDWzVKr,c3vxNbb,XKBQ7KV,vCnfVmz,sgvh6r6,ZpDpZRL,nvwLFsH,brZpgjN,Q8KtmBW,xHVQWWf,33bwxhV,q2hdcdH,tSfzSZq,sqkDJqb,nLSwzt2,PCVb5BM,z9XVqS6,PpFtc94,W8zcNjx,RD4mp3J,Z8b4VfZ,RHjH79S,L2k54gN,xdQd3ww,Xznbmhr,ws7MQnS,GBMHVw4,J7znxDf,KtSdS8k,KG6hbf4,hShrHKK,FkTczCC,LNLxknm,t6NZnnT,T5msfBv,8GW5Rj8,FxLJ8f2,MS4X46H,6xGQtk9,DxZZqvS,8xr4KB4,L84SNXJ,kQL8tfc,37gkHLn,HCt6Vpj,N2xHsb5,bmnNVRB,gC98nx9,WwgQf8v,CspqFF7,GSTNTvq,k58Jqvs,XGPHFML,Ds7t5K5,qfhPNpD,XrDRhDn,QXKGvsG,QPRc3RN,79tLNht,G76txxZ,4rvVhSq,WP5T4n8,4BWnvT6,Q5FwVhm,bTq4729,7M9kMx9,rq9dNfR,tknpTC5,bFnC9qn,pWpdH77,2Zr7GH4,PQSx54L,4kWG9m5,SxVWhnQ,tczDZMj,tkLdVsv,b8HHPvm,7Gh4X7n,SJtHVtg,kJKtKpC,JCG73xB,PBbzsvc,ZdRpLL7,PvL9Hz8,q5BZLwX,2DPsjPL,4bzTjTJ,qHMVGnS,tQt47RR,QDCzVXn,b2KpMGJ,hHdNkbz,rRkttvW,K6VZFtM,pHSvQLk,S7JM8cL,jw7cqmX,CjmLNX2,nWHVKxJ,9zhBcqN,C8959JL,FsqFxSs,GckS5Sv,Br8mnFs,RWQ4BXd,jh56ttW,D8d7CGT,WD3rNSV,bB6FcQ7,LpGq2Dk!sizecustom
on this server.</p>
</body></html>
/home/will/local/history-project/_plugins/smugmug_album.rb:46:in `fetch_image_urls': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/will/local/history-project/_plugins/smugmug_album.rb:60:in `fetch_album'
	from /home/will/local/history-project/_plugins/smugmug_album.rb:89:in `get_show_photos'
	from /home/will/local/history-project/_plugins/show.rb:108:in `get_show_smugmug'
	from /home/will/local/history-project/_plugins/show.rb:179:in `generate_show'
	from /home/will/local/history-project/_plugins/show.rb:245:in `block in generate'
	from /home/will/local/history-project/_plugins/show.rb:245:in `each'
	from /home/will/local/history-project/_plugins/show.rb:245:in `generate'
	from /var/lib/gems/2.3.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:174:in `block in generate'
	from /var/lib/gems/2.3.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:172:in `each'
	from /var/lib/gems/2.3.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:172:in `generate'
	from /var/lib/gems/2.3.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:68:in `process'
	from /var/lib/gems/2.3.0/gems/jekyll-3.3.0/lib/jekyll/command.rb:26:in `process_site'
	from /var/lib/gems/2.3.0/gems/jekyll-3.3.0/lib/jekyll/commands/build.rb:63:in `build'
	from /var/lib/gems/2.3.0/gems/jekyll-3.3.0/lib/jekyll/commands/build.rb:34:in `process'
	from /var/lib/gems/2.3.0/gems/jekyll-3.3.0/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /var/lib/gems/2.3.0/gems/jekyll-3.3.0/exe/jekyll:13:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by davidtaylorhq** [comment]
Can this go away now that #697 is merged?

**Comment by BenWoodford76** [comment]
@wjdp @nhyty??

**Comment by wjdp** [comment]
The bug is still present in the codebase, we've just set a workaround.

To clean things up I'll close this, but it should be re-opened if a use case for fetching a large number of images comes up.
